### ISSUE TITLE
Version 1.6 does not always provision an agent

### ISSUE THREAD

**Issue by steve-todorov** [jenkinsci/docker-swarm-plugin#26]
After upgrading to 1.6 our agents are not always being provisioned. Every X times, the provisioned agent becomes "stale" and is not created at all. Doing `docker service ls` shows that a service is created, but no replicas are created. When you go to the agent's details it says the following error:

![image](https://user-images.githubusercontent.com/2303663/50498972-0179d800-0a4e-11e9-9192-b05d891e43bf.png)

![image](https://user-images.githubusercontent.com/2303663/50498994-325a0d00-0a4e-11e9-8207-8e1db339c311.png)

Here is some information I managed to gather from the swarm:

```
root@swarm:~# docker service inspect ukeeoulxp8k5
[
    {
        "ID": "ukeeoulxp8k5i2fge7cnpbpm2",
        "Version": {
            "Index": 73260
        },
        "CreatedAt": "2018-12-28T01:02:04.139851038Z",
        "UpdatedAt": "2018-12-28T01:02:04.139851038Z",
        "Spec": {
            "Name": "agent-ox___master__24-53968",
            "Labels": {
                "ROLE": "jenkins-agent"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "my-image/alpine:nuget-3.4-mono",
                    "Command": [
                        "sh",
                        "-cx",
                        "curl --connect-timeout 20 --max-time 60 -o slave.jar $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL \u0026\u0026 java -jar slave.jar -jnlpUrl $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL -secret $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET -noReconnect -workDir /tmp"
                    ],
                    "Env": [
                        "DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET=09c2d3df2d0fb1ee3e014544f29b96a3f539a87ace4bcd42f9ef6e1d1ba4a773",
                        "DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL=http://10.0.0.8:8080/jnlpJars/slave.jar",
                        "DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL=http://10.0.0.8:8080/computer/agent-ox___master__24-53968/slave-agent.jnlp"
                    ],
                    "Dir": "/home/jenkins",
                    "User": "root",
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/etc/hostname",
                            "Target": "/etc/node"
                        },
                        {
                            "Type": "bind",
                            "Source": "/cache",
                            "Target": "/cache"
                        },
                        {
                            "Type": "bind",
                            "Source": "/mnt/ramdisk/workspace",
                            "Target": "/home/jenkins/workspace"
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {
                        "NanoCPUs": 8000000000,
                        "MemoryBytes": 8000000000
                    }
                },
                "RestartPolicy": {
                    "Condition": "none",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Constraints": [
                        "node.labels.jenkins == agent"
                    ]
                },
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            }
        },
        "Endpoint": {
            "Spec": {}
        }
    }
]
root@swarm:~# 
root@swarm:~# docker service logs ukeeoulxp8k5
root@swarm:~# (no logs)
```

This happens very often on pipeline jobs which are using `parallel` to run stages in parallel. All of the images we use have `jdk8` installed and they used to work just fine with `1.5`.

Downgrading to 1.5 fixes things and I suspect it has to do with some of the changes that have been done with the 1.6 release. Let me know if there is any way I can help with debugging this issue.

**Comment by smhc** [comment]
Could you try this release which uses a more unique agent name: https://github.com/smhc/docker-swarm-plugin-tls/releases/tag/v0.1

**Comment by steve-todorov** [comment]
Hi @smhc and thanks for your fast response! I just tried your release, and it doesn't seem to be working for us. The agent's log shows a NPE:

```
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
java.lang.NullPointerException
	at org.jenkinsci.plugins.docker.swarm.DockerSwarmCloud.getDockerSwarmApiUrl(DockerSwarmCloud.java:151)
	at org.jenkinsci.plugins.docker.swarm.docker.api.request.ApiRequest.<init>(ApiRequest.java:66)
	at org.jenkinsci.plugins.docker.swarm.docker.api.service.ServiceSpec.<init>(ServiceSpec.java:25)
	at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.createCreateServiceRequest(DockerSwarmComputerLauncher.java:160)
	at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.launchContainer(DockerSwarmComputerLauncher.java:119)
	at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.launch(DockerSwarmComputerLauncher.java:101)
	at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.launch(DockerSwarmComputerLauncher.java:56)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Is there any particular reason for changing the naming of the agents? Maybe it will work fine if the naming is reverted back to `agent-truncatedNanoTime` ?

**Comment by smhc** [comment]
That looks like a problem with the config. You may need to uninstall the old plugin and re-install and re-configure the plugin using the .hpi installation.

> Is there any particular reason for changing the naming of the agents? 

It makes tracking containers in the swarm back to jobs in jenkins much easier. Looking at the swarm dashboard is not very informative when the services are all 'agent-<random>'.

It just needs to be unique - the changes as part of this fix are actually more unique than using the 'nano time', as it includes an incremented counter value. The nanotime part should probably be removed, but may still be useful for when jenkins is restarted.

You could also go into the 'system log' section of jenkins and add a logger for 'org.jenkinsci.plugins.docker.swarm' to help track down the problem.

**Comment by steve-todorov** [comment]
> That looks like a problem with the config.

It seems like you're right - I uninstalled the plugin, restarted Jenkins, installed it again and reconfigured everything from scratch. Now everything works as expected. 

> It makes tracking containers in the swarm back to jobs in jenkins much easier

To be honest, I never use the swarm dashboard. All of our jobs have a "stage" which contains information regarding the node and the tools which are being used on the image so we rarely ever need to use the dashboard. Although I understand your reasoning, the agent names are now quite long if you have "folder(s)" and then multibranch pipelines:

![image](https://user-images.githubusercontent.com/2303663/50699349-47d3c600-1050-11e9-87a5-1e1c72323e5b.png)

Is there anything else that could be done? Maybe this string could be hashed into `md5` and then shortened to 8 characters for example?

**Comment by smhc** [comment]
So you don't have issues with provisioning agents any more with this fix? Presumably it was an issue with non-unique agent names.

The agent name can be anything unique, it's just a matter of how human readable and useful it is. The name is also used as the docker container name, so when looking at running containers it makes it much easier to trace it back to a jenkins job.

We could go with a shorter truncation of the job name, plus the incrementing counter, and do away with the random number. We could also shorten agent to 'agt', so something like;

agt-blah_master_xyz-3

**Comment by steve-todorov** [comment]
Sorry for the delayed reply.

Yes, things have been working as expected for the past few days. Most likely the issue was indeed the uniqueness of the agent name.

As for the agent naming - your idea is actually good. Maybe something like `my_job_name_up_to_20chars-BUILD_NUMBER-RANDOM_6_DIGITS`? Removing the `agent-` part frees 6 chars. If you use only single `_` in the string it should also free a couple characters more and it should look a bit better with longer names. What are your thoughts?

**Comment by smhc** [comment]
Ok that's good, I'll submit a pull request with some changes.

The common prefix is useful because the agent, container and node are all given the same name. It's useful to have a common prefix in jenkins with all the nodes that are actually docker containers. Otherwise the nodes will all have random names and it would be a mess.

I've also chosen to use the last x characters of the job, as that is generally more useful than the first x characters when using pipelines (e.g. part x of x) or folders. 

I'm not sure the build number is available but even if it were, it's not unique unless you combine it with the full job name, which we aren't using. So it's not as useful as a global counter.
