### ISSUE TITLE
Randomly stucked in "Remote identity confirmed"

### ISSUE THREAD

**Issue by maiconbaumx** [jenkinsci/docker-swarm-plugin#59]
Hello guys,
I'm facing an issue while using this plugin in Jenkins. Sometimes, randomly, an agent stuck during launch process in the step "QINFO: Remote identity confirmed". IDK if my usage can be the root cause of this, sometimes I have a peak usage with something about 20~25 agents running simultaneously. If I log in to the Docker host, attach to this agent-container and manually run the java process again, everything works. Any idea how to solve this? 

I'm running Jenkins on CentOS 7x and its version is 2.190.1. The plugin version is 1.8 and the Docker version is 19.03.1. 

Here is the agent log:

```
[5:22:22 PM] Creating Service with Name : agt-ploy_internal_9-349
[5:22:22 PM] ServiceSpec created with ID : panqipod9ov7c6lezwbuav463
[5:22:22 PM] ServiceSpec request JSON : {"TaskTemplate":{"ContainerSpec":{"Image":"xxxxx.xxxxxx.xxxxxx/ci-slave-nodejs:latest-11x","Command":["sh","-cx","curl --connect-timeout 20 --max-time 60 -o agent.jar $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL && java -jar agent.jar -jnlpUrl $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL -secret $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET -noReconnect -workDir /tmp"],"Env":["GRADLE_CACHE=/home/jenkins/job-cache","SLAVE_HOME=/home/jenkins","DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET=xxxxxxxxxxxxxxxxxxx","DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL=http://xxxxx.xxxxxx.xxx:8080/jnlpJars/agent.jar","DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL=http://xxxxx.xxxxxx.xxxxxx:8080/computer/agt-ploy_internal_9-349/slave-agent.jnlp","DOCKER_SWARM_PLUGIN_JENKINS_AGENT_NAME=agt-ploy_internal_9-349"],"Dir":"/home/jenkins","User":"jenkins","DNSConfig":{"Nameservers":[],"Search":[],"Options":[]},"Mounts":[{"Target":"/home/jenkins/.m2","Source":"/home/jenkins/.m2","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/.ivy2","Source":"/home/jenkins/.ivy2","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/.gradle","Source":"/home/jenkins/.gradle","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/.sbt","Source":"/home/jenkins/.sbt","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/.dockercfg","Source":"/home/jenkins/.dockercfg","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/job-cache","Source":"/jenkins_cache","Type":"bind","VolumeOptions":null},{"Target":"/var/run/docker.sock","Source":"/var/run/docker.sock","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/.ssh","Source":"/home/jenkins/.ssh","Type":"bind","VolumeOptions":null},{"Target":"/tmp/meta","Source":"/tmp/meta","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/.pip","Source":"/home/jenkins/.pip","Type":"bind","VolumeOptions":null},{"Target":"/home/jenkins/.npmrc","Source":"/home/jenkins/.npmrc","Type":"bind","VolumeOptions":null}],"Hosts":[],"Secrets":[],"Configs":[]},"RestartPolicy":{"Condition":"none","MaxAttempts":0},"Resources":{"Limits":{"NanoCPUs":0,"MemoryBytes":2621440000},"Reservations":{"NanoCPUs":0,"MemoryBytes":0}},"Placement":{"Constraints":[]}},"Name":"agt-ploy_internal_9-349","Labels":{"ROLE":"jenkins-agent"},"Networks":[]}
n+ curl --connect-timeout 20 --max-time 60 -o agent.jar http://xxxxx.xxxxxx.xxxxxx:8080/jnlpJars/agent.jar
P  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
N                                 Dload  Upload   Total   Spent    Left  Speed
�
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  851k  100  851k    0     0  6344k      0 --:--:-- --:--:-- --:--:-- 6358k
�+ java -jar agent.jar -jnlpUrl http://xxxxx.xxxxxx.xxxxxx:8080/computer/agt-ploy_internal_9-349/slave-agent.jnlp -secret xxxxxxxxxxxxxxxxxxx -noReconnect -workDir /tmp
WOct 18, 2019 8:22:25 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
7INFO: Using /tmp/remoting as a remoting work directory
ROct 18, 2019 8:22:25 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
BINFO: Both error and output logs will be printed to /tmp/remoting
?Oct 18, 2019 8:22:25 PM hudson.remoting.jnlp.Main createEngine
0INFO: Setting up agent: agt-ploy_internal_9-349
EOct 18, 2019 8:22:25 PM hudson.remoting.jnlp.Main$CuiListener <init>
1INFO: Jenkins agent is running in headless mode.
;Oct 18, 2019 8:22:25 PM hudson.remoting.Engine startEngine
#INFO: Using Remoting version: 3.33
WOct 18, 2019 8:22:25 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
7INFO: Using /tmp/remoting as a remoting work directory
EOct 18, 2019 8:22:25 PM hudson.remoting.jnlp.Main$CuiListener status
[INFO: Locating server among [http://xxxxx.xxxxxx.xxxxxx:8080/, https://xxxxx.xxxxxx.xxxxxx/]
XOct 18, 2019 8:22:26 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
MINFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
EOct 18, 2019 8:22:26 PM hudson.remoting.jnlp.Main$CuiListener status
!INFO: Agent discovery successful
)  Agent address: xxxxx.xxxxxx.xxxxxx
  Agent port:    8090
A  Identity:      45:d5:f9:c2:7d:f7:9a:98:a7:6c:f5:9f:9c:25:10:6f
EOct 18, 2019 8:22:26 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
EOct 18, 2019 8:22:26 PM hudson.remoting.jnlp.Main$CuiListener status
1INFO: Connecting to xxxxx.xxxxxx.xxxxxx:8090
EOct 18, 2019 8:22:26 PM hudson.remoting.jnlp.Main$CuiListener status
%INFO: Trying protocol: JNLP4-connect
EOct 18, 2019 8:22:26 PM hudson.remoting.jnlp.Main$CuiListener status
QINFO: Remote identity confirmed: 45:d5:f9:c2:7d:f7:9a:98:a7:6c:f5:9f:9c:25:10:6f
```

**Comment by Roemer** [comment]
Hi @maiconbaumx 
I once encountered exactly the same. I currently have no idea what the issue could be here. Not sure that it is related to docker swarm. Maybe the Jenkins agent has an issue every 100th launch or so. I was never able to reproduce the issue. How often does it happen to you?

**Comment by maiconbaumx** [comment]
Hi @Roemer
This was happening like once per day. But here is the thing: I'm using a custom image, based on Debian 9, with custom runtimes for my build flavors. Before moving to Docker Swarm plugin, I was using Docker Plugin and my containers were booting with the jenkins-slave script as `ENTRYPOINT` and when I moved to use Docker Swarm Plugin, I have added the` CMD` section as described in the documentation plugin's and I forgot about the old `ENTRYPOINT` section, that is, there were two agents starting with container boot. No issues around this. Just one of this agents was connecting fine and it was doing it's job, but I had this issue eventualy. So, I found this `ENTRYPOINT` section while reviewing my set of images and I removed this section in order to stop` jenkins-slave` being started during container boot and I've just let the `CMD` section as it was before and now, there is no problem anymore. This issue aparently disappeared!

Maybe that could be an inconsistency between the JNLP Agent started by `ENTRYPOINT` section and the agent started by` CMD` section, IDK, but it's ok now. Thanks a lot. =)

**Comment by maiconbaumx** [comment]
Sorry, actually, this is yet occurring.  :(
This is happening like twice per day, randomly. Do you need to know the interval between triggered agents in which this occurs? I can try to measure this.

**Comment by maiconbaumx** [comment]
I was able to connect to an agent while this error happened and I found a deadlock on Java process using jstack. Here it is:

`jenkins@c520460cb34a:~$ jstack 8
2019-11-06 21:07:57
Full thread dump OpenJDK 64-Bit Server VM (11.0.4+11 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007fb058001c50, length=14, elements={
0x00007fb0a0011800, 0x00007fb0a0248800, 0x00007fb0a024c800, 0x00007fb0a0260800,
0x00007fb0a0262800, 0x00007fb0a0264800, 0x00007fb0a0266800, 0x00007fb0a02f4000,
0x00007fb0a02ff800, 0x00007fb0a06a1000, 0x00007fb03800a800, 0x00007fb03800c800,
0x00007fb038064800, 0x00007fb058001000
}

"main" #1 prio=5 os_prio=0 cpu=782.72ms elapsed=13585.05s tid=0x00007fb0a0011800 nid=0x9 in Object.wait()  [0x00007fb0a80d7000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <0x0000000707d770c0> (a hudson.remoting.Engine)
	at java.lang.Thread.join(java.base@11.0.4/Thread.java:1305)
	- waiting to re-lock in wait() <0x0000000707d770c0> (a hudson.remoting.Engine)
	at java.lang.Thread.join(java.base@11.0.4/Thread.java:1379)
	at hudson.remoting.jnlp.Main.main(Main.java:229)
	at hudson.remoting.jnlp.Main._main(Main.java:222)
	at hudson.remoting.Launcher.run(Launcher.java:365)
	at hudson.remoting.Launcher.main(Launcher.java:283)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.70ms elapsed=13585.01s tid=0x00007fb0a0248800 nid=0x10 waiting on condition  [0x00007fb063ffe000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.4/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.4/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.4/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.57ms elapsed=13585.01s tid=0x00007fb0a024c800 nid=0x11 in Object.wait()  [0x00007fb063efd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.4/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000707d86760> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.4/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.4/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.40ms elapsed=13585.00s tid=0x00007fb0a0260800 nid=0x12 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 cpu=984.69ms elapsed=13585.00s tid=0x00007fb0a0262800 nid=0x13 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=710.00ms elapsed=13585.00s tid=0x00007fb0a0264800 nid=0x14 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #8 daemon prio=9 os_prio=0 cpu=16.84ms elapsed=13585.00s tid=0x00007fb0a0266800 nid=0x15 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #9 daemon prio=9 os_prio=0 cpu=0.16ms elapsed=13584.96s tid=0x00007fb0a02f4000 nid=0x16 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #10 daemon prio=8 os_prio=0 cpu=17.32ms elapsed=13584.95s tid=0x00007fb0a02ff800 nid=0x18 in Object.wait()  [0x00007fb063682000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.4/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000707d871b8> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.4/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.4/InnocuousThread.java:134)

"Thread-0" #13 prio=5 os_prio=0 cpu=346.71ms elapsed=13584.13s tid=0x00007fb0a06a1000 nid=0x1b waiting on condition  [0x00007fb062209000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x0000000716b203d0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.4/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.4/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(java.base@11.0.4/AbstractQueuedSynchronizer.java:1009)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@11.0.4/AbstractQueuedSynchronizer.java:1324)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@11.0.4/ReentrantReadWriteLock.java:738)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.getNextSend(ProtocolStack.java:841)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doSend(ProtocolStack.java:685)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:518)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	- locked <0x0000000716b1be20> (a java.lang.Object)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doSend(ProtocolStack.java:691)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.doSend(ConnectionHeadersFilterLayer.java:497)
	- locked <0x0000000716b16358> (a org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doSend(ProtocolStack.java:691)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.write(ApplicationLayer.java:157)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.start(ChannelApplicationLayer.java:230)
	at org.jenkinsci.remoting.protocol.ProtocolStack.init(ProtocolStack.java:201)
	at org.jenkinsci.remoting.protocol.ProtocolStack.access$700(ProtocolStack.java:106)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Builder.build(ProtocolStack.java:554)
	at org.jenkinsci.remoting.engine.JnlpProtocol4Handler.connect(JnlpProtocol4Handler.java:179)
	at org.jenkinsci.remoting.engine.JnlpProtocolHandler.connect(JnlpProtocolHandler.java:157)
	at hudson.remoting.Engine.innerRun(Engine.java:573)
	at hudson.remoting.Engine.run(Engine.java:474)

"IOHub#1: Selector[keys:0, gen:0] / pool-1-thread-1" #14 daemon prio=5 os_prio=0 cpu=999.46ms elapsed=13584.12s tid=0x00007fb03800a800 nid=0x1c runnable  [0x00007fb062109000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.4/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.4/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.4/SelectorImpl.java:124)
	- locked <0x0000000707dcee80> (a sun.nio.ch.Util$2)
	- locked <0x0000000707dced10> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.4/SelectorImpl.java:141)
	at org.jenkinsci.remoting.protocol.IOHub.run(IOHub.java:461)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at hudson.remoting.Engine$1$$Lambda$46/0x000000080014f040.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"Windows IOHub Watcher for IOHub#1: Selector[keys:0, gen:0] / pool-1-thread-2" #15 daemon prio=5 os_prio=0 cpu=933.80ms elapsed=13584.12s tid=0x00007fb03800c800 nid=0x1d in Object.wait()  [0x00007fb062008000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <no object reference available>
	at org.jenkinsci.remoting.protocol.IOHub$IOHubSelectorWatcher.run(IOHub.java:549)
	- waiting to re-lock in wait() <0x0000000707d879d8> (a java.lang.Object)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at hudson.remoting.Engine$1$$Lambda$46/0x000000080014f040.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"pool-1-thread-3" #16 daemon prio=5 os_prio=0 cpu=578.24ms elapsed=13583.93s tid=0x00007fb038064800 nid=0x22 waiting for monitor entry  [0x00007fb0618ff000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvRemoved(FilterLayer.java:134)
	- waiting to lock <0x0000000716b16358> (a org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.getNextRecv(ProtocolStack.java:913)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:662)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processRead(SSLEngineFilterLayer.java:369)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecv(SSLEngineFilterLayer.java:117)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:668)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRead(NetworkLayer.java:136)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$2200(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:283)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at hudson.remoting.Engine$1$$Lambda$46/0x000000080014f040.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"Attach Listener" #18 daemon prio=9 os_prio=0 cpu=0.41ms elapsed=0.10s tid=0x00007fb058001000 nid=0x61 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=527.59ms elapsed=13585.02s tid=0x00007fb0a0240000 nid=0xf runnable

"GC Thread#0" os_prio=0 cpu=19.42ms elapsed=13585.04s tid=0x00007fb0a0027000 nid=0xa runnable

"GC Thread#1" os_prio=0 cpu=9.51ms elapsed=13584.07s tid=0x00007fb068001000 nid=0x1e runnable

"GC Thread#2" os_prio=0 cpu=9.75ms elapsed=13584.07s tid=0x00007fb068002800 nid=0x1f runnable

"GC Thread#3" os_prio=0 cpu=16.45ms elapsed=13584.07s tid=0x00007fb068004000 nid=0x20 runnable

"G1 Main Marker" os_prio=0 cpu=0.96ms elapsed=13585.04s tid=0x00007fb0a0084800 nid=0xb runnable

"G1 Conc#0" os_prio=0 cpu=0.08ms elapsed=13585.04s tid=0x00007fb0a0086000 nid=0xc runnable

"G1 Refine#0" os_prio=0 cpu=3.64ms elapsed=13585.04s tid=0x00007fb0a0175800 nid=0xd runnable

"G1 Refine#1" os_prio=0 cpu=0.10ms elapsed=13584.06s tid=0x00007fb070001000 nid=0x21 runnable

"G1 Young RemSet Sampling" os_prio=0 cpu=2153.32ms elapsed=13585.04s tid=0x00007fb0a0177000 nid=0xe runnable
"VM Periodic Task Thread" os_prio=0 cpu=13962.96ms elapsed=13584.96s tid=0x00007fb0a02f6800 nid=0x17 waiting on condition

JNI global refs: 19, weak refs: 0


Found one Java-level deadlock:
=============================
"Thread-0":
  waiting for ownable synchronizer 0x0000000716b203d0, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "pool-1-thread-3"
"pool-1-thread-3":
  waiting to lock monitor 0x00007fb014008c00 (object 0x0000000716b16358, a org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer),
  which is held by "Thread-0"

Java stack information for the threads listed above:
===================================================
"Thread-0":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x0000000716b203d0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.4/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.4/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(java.base@11.0.4/AbstractQueuedSynchronizer.java:1009)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@11.0.4/AbstractQueuedSynchronizer.java:1324)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@11.0.4/ReentrantReadWriteLock.java:738)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.getNextSend(ProtocolStack.java:841)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doSend(ProtocolStack.java:685)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:518)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	- locked <0x0000000716b1be20> (a java.lang.Object)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doSend(ProtocolStack.java:691)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.doSend(ConnectionHeadersFilterLayer.java:497)
	- locked <0x0000000716b16358> (a org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doSend(ProtocolStack.java:691)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.write(ApplicationLayer.java:157)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.start(ChannelApplicationLayer.java:230)
	at org.jenkinsci.remoting.protocol.ProtocolStack.init(ProtocolStack.java:201)
	at org.jenkinsci.remoting.protocol.ProtocolStack.access$700(ProtocolStack.java:106)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Builder.build(ProtocolStack.java:554)
	at org.jenkinsci.remoting.engine.JnlpProtocol4Handler.connect(JnlpProtocol4Handler.java:179)
	at org.jenkinsci.remoting.engine.JnlpProtocolHandler.connect(JnlpProtocolHandler.java:157)
	at hudson.remoting.Engine.innerRun(Engine.java:573)
	at hudson.remoting.Engine.run(Engine.java:474)
"pool-1-thread-3":
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvRemoved(FilterLayer.java:134)
	- waiting to lock <0x0000000716b16358> (a org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.getNextRecv(ProtocolStack.java:913)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:662)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processRead(SSLEngineFilterLayer.java:369)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecv(SSLEngineFilterLayer.java:117)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:668)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRead(NetworkLayer.java:136)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$2200(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:283)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at hudson.remoting.Engine$1$$Lambda$46/0x000000080014f040.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

Found 1 deadlock.`
