### ISSUE TITLE
TLS authentication configuration documentation

### ISSUE THREAD

**Issue by gynter** [jenkinsci/docker-swarm-plugin#69]
Hello! I have set up Jenkins in a Docker container. A Docker API proxy is set up as described [here](https://medium.com/faun/how-to-access-and-secure-the-docker-engine-api-in-docker-swarm-for-aws-a5d67db2c417) using certificate authentication (except for the server cert part, I'm using a cert from our CA for the server). The proxy works fine (tested with curl).

Then I made a custom keystore (due to snakeoil CA) and passed `-Djavax.net.ssl.trustStore=/path/to/cakeystore` to jvm. The keystore works fine. I tested with another Jenkins plugin, which also creates connections over TLS using the same CA. When removing the trustStore option, another plugin fails to create connection, as it should.

Then I added a X509 credentials using the cert (which is used to Docker API proxy) and it's key. As *Server CA Certificate* I have tried the server cert, it's CA cert and even empty value, but without a luck. The result when pressing *Test Connection* is `javax.net.ssl.SSLPeerUnverifiedException: Hostname docker-test not verified`.

When server CA certificate is left empty, the test returns:
```
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.github.dockerjava.core.util.CertificateUtils.createTrustStore(CertificateUtils.java:174)
	at org.jenkinsci.plugins.docker.swarm.DockerServerCredentialsSSLConfig.getSSLContext(DockerServerCredentialsSSLConfig.java:41)
	at org.jenkinsci.plugins.docker.swarm.DockerSwarmCloud.getSSLContext(DockerSwarmCloud.java:164)
Caused: java.io.IOException: Failed to create SSL Config 
	at org.jenkinsci.plugins.docker.swarm.DockerSwarmCloud.getSSLContext(DockerSwarmCloud.java:167)
	at org.jenkinsci.plugins.docker.swarm.docker.api.request.ApiRequest.<init>(ApiRequest.java:69)
```
If I don't set credentials at all (as ` - none - `), I get this response: `javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

I also tried to use the `skip-certificate-check` plugin, but without luck.

Any clues, what I'm doing wrong on credentials configuration?

**Comment by David-Villeneuve** [comment]
It took awhile to figure out where this was all going wrong for me. 

Effectively, the ca and keys between docker manager and workers is not the keys/tokens you need for jenkins. These are separate.  You want the keys needed for "clients" talking to docker over the network.

In my case, I followed the docker documentation on how to secure access to docker, making my own internal CA, and then used it to sign server and client keys.  I then setup docker to communicate via port 5555 on the main external IP with all the --tls* options they recommend. 

On my Jenkins host I added the CA certificate to my java keystore as a trusted CA.

While docker swarm will communicate on a different port with manager/workers, this is not the port jenkins wants to talk to.  In my case, it was the 5555 port I setup in my ExecStart line with "-H 0.0.0.0:5555".

The swarm plug-in wants to use SSL, and for this you need to setup an x509 credential.  For this you need to provide the serve CA certificate, the client certificate, and the client-key, and this last one is where things go wrong.  OpenSSL on Ubuntu-18 did not provide this in a basic text format.  I had to convert the key:

mv key.pem key.bak
openssl rsa -in key.bak -text > key.pem

The text key works, but here's the other funky thing .... when you setup the swarm and enter this certificate, save the settings, then go back to configure cloud, and then when you test, it should work (it does not work unless you save this first).  

I hope this saves someone out there alot of time ... I know if I'd known about this, I'd be a lot further ahead.
