### ISSUE TITLE
NullPointerException when launching agent in jenkinsfile runner

### ISSUE THREAD

**Issue by lehenric** [jenkinsci/docker-swarm-plugin#75]
Hi,
I am getting `java.lang.NullPointerException` when trying to run Docker Swarm Plugin in jenkinsfile runner docker image configured with JCasC.

Stacktrace from `slave.log`:
```log
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
java.lang.NullPointerException
        at org.jenkinsci.plugins.docker.swarm.docker.api.service.ServiceSpec.setAuthHeader(ServiceSpec.java:116)
        at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.setAuthHeaders(DockerSwarmComputerLauncher.java:299)
        at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.launchContainer(DockerSwarmComputerLauncher.java:141)
        at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.launch(DockerSwarmComputerLauncher.java:105)
        at org.jenkinsci.plugins.docker.swarm.DockerSwarmComputerLauncher.launch(DockerSwarmComputerLauncher.java:59)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:291)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

JCasC `jenkins.yml`:
```yml
jenkins:
  clouds:
  - dockerSwarm:
      agentTemplates:
      - command: |-
          sh
          -eucx
          curl --connect-timeout 20 --max-time 60 -o agent.jar $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL && java -jar agent.jar -jnlpUrl $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL -secret $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET -noReconnect -workDir /tmp                                                                               
        pullCredentialsId: "registry-reader"
        image: "buildagent:0.1.0"
        label: "node"
        limitsMemoryBytes: 0
        limitsNanoCPUs: 0
        osWindows: false
        reservationsMemoryBytes: 0
        reservationsNanoCPUs: 0
        workingDir: "/tmp"
      dockerHost:
        uri: "http://10.0.1.5:51234"
      dockerSwarmApiUrl: "http://10.0.1.5:51234"
      jenkinsUrl: "http://jenkins/jenkins"
      swarmNetwork: "jenkins-network"
```

When I am trying to replicate this in normal jenkins docker image (not jenkinsfile runner), I am unable to get this error and agent starts up without problems.

I tried setting up `email` and `serverAddress` in agentTemplate ( from stacktrace: `ServiceSpec.java:116`) without any success.

Any ideas if this is caused by wrong configuration or it is really a bug in docker-swarm plugin?

**Comment by lehenric** [comment]
Update: 
It seems JCasC was not being sourced correctly. 
With `email` and `serverAddress` as empty strings, execution continues as expected.
