### ISSUE TITLE
[BUG] NullPointerException when reset-stuck-builds-actor triggers

### ISSUE THREAD

**Issue by Polpetta** [jenkinsci/docker-swarm-plugin#93]
Hi,
as per title, there is a `NullPointerException` when the actor that resets the builds that are stuck triggers.
This is the stacktrace:
```java
[ERROR] [10/06/2020 16:58:15.311] [swarm-plugin-akka.actor.default-dispatcher-61] [akka://swarm-plugin/user/reset-stuck-builds-actor] null
java.lang.NullPointerException
        at org.jenkinsci.plugins.docker.swarm.ResetStuckBuildsInQueueActor.resetStuckBuildsInQueue(ResetStuckBuildsInQueueActor.java:32)
        at org.jenkinsci.plugins.docker.swarm.ResetStuckBuildsInQueueActor.lambda$createReceive$0(ResetStuckBuildsInQueueActor.java:23)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
        at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:227)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I think that the bug is due to a `null` being returned when `DockerSwarmCloud.get()` is invoked.

**Comment by markixy** [comment]
i still see this error.
```sh
[ERROR] [12/29/2023 16:49:22.691] [swarm-plugin-akka.actor.default-dispatcher-47] [akka://swarm-plugin/user/reset-stuck-builds-actor] null
java.lang.NullPointerException
	at org.jenkinsci.plugins.docker.swarm.ResetStuckBuildsInQueueActor.resetStuckBuildsInQueue(ResetStuckBuildsInQueueActor.java:36)
	at org.jenkinsci.plugins.docker.swarm.ResetStuckBuildsInQueueActor.lambda$createReceive$0(ResetStuckBuildsInQueueActor.java:27)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:227)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**context**
jenkins2.426.2
just install “Docker Swarm Plugin 1.11” plugin，swarm cloud has not been yet configured
